<?php

namespace OC\CoreBundle\Repository;

/**
 * ClosingdaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClosingdaysRepository extends \Doctrine\ORM\EntityRepository
{
}
