<?php

namespace OC\CoreBundle\Repository;

/**
 * ClosingdaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClosingdaysRepository extends \Doctrine\ORM\EntityRepository
{
    public function testVisitDay($value) 
    {
        $qb = $this->createQueryBuilder('c');
        
        $qb
          ->where('c.closingDay = :closingDay')
          ->setParameter('closingDay', $value)
        ;

        return $qb
        ->getQuery()
        ->getResult()
        ;
    
    }
}
