<?php

namespace OC\CoreBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTicketsNbforaDay($testVisitDay) 
    {
        $qb = $this->createQueryBuilder('t')
        ->select('COUNT(t)')
        ->innerJoin('t.booking', 'b','WITH', 'b.bookingCode IS NOT NULL')
        ->where('b.visitDay = :visitDay')
        ->setParameter('visitDay', $testVisitDay);

        return $qb
        ->getQuery()
        ->getSingleScalarResult();
    }
        
}
