oc_core_homepage:
    path:     /
    defaults: { _controller: OCCoreBundle:Welcome:index }

oc_core_add:
    path:     /add
    defaults: { _controller: OCCoreBundle:Booking:add }

oc_core_visitors:
        path:     /visitors
        defaults: { _controller: OCCoreBundle:Booking:visitors }

oc_core_recap:
        path:     /recap
        defaults: { _controller: OCCoreBundle:Booking:recap }