services:
#    oc_core.example:
#        class: OC\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    OC\CoreBundle\DataFixtures\ORM\LoadRate:
            tags: [doctrine.fixture.orm]

    OC\CoreBundle\DataFixtures\ORM\LoadDuration:
            tags: [doctrine.fixture.orm]

    OC\CoreBundle\DataFixtures\ORM\LoadClosingdays:
            tags: [doctrine.fixture.orm]

    oc_core.validator.AntiClosingDays:                             
        class: OC\CoreBundle\Validator\AntiClosingDaysValidator     
        arguments: ["@doctrine.orm.entity_manager"] 
        tags:
            - { name: validator.constraint_validator, alias: oc_core_AntiClosingDays }  

    oc_core.servstripe:
        class: OC\CoreBundle\ServStripe\OCServStripe

    oc_core.servemail:
        class: OC\CoreBundle\ServEmail\OCServEmail
        arguments: 
            - '@templating'
            - '@translator'
            
        


