services:
#    oc_core.example:
#        class: OC\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    OC\CoreBundle\:
        resource: OC\CoreBundle\*

    OC\CoreBundle\DataFixtures\ORM\LoadRate:
            tags: [doctrine.fixture.orm]

    OC\CoreBundle\DataFixtures\ORM\LoadDuration:
            tags: [doctrine.fixture.orm]

    OC\CoreBundle\DataFixtures\ORM\LoadClosingdays:
            tags: [doctrine.fixture.orm]

    oc_core.validator.AntiClosingDays:                             
        class: OC\CoreBundle\Validator\AntiClosingDaysValidator     
        arguments: ["@doctrine.orm.entity_manager", "@oc_core.servclosingdays"] 
        tags:
            - { name: validator.constraint_validator, alias: oc_core_AntiClosingDays }  

    oc_core.servstripe:
        class: OC\CoreBundle\ServStripe\OCServStripe

    oc_core.servemail:
        class: OC\CoreBundle\ServEmail\OCServEmail
        arguments: 
            - '@templating'
            - '@translator'
            
    oc_core.validator.AntiMaxTicketsNb:                             
        class: OC\CoreBundle\Validator\AntiMaxTicketsNbValidator     
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"] 
        tags:
            - { name: validator.constraint_validator, alias: oc_core_AntiMaxTicketsNb }  

    oc_core.servclosingdays:
        class: OC\CoreBundle\ServClosingDays\OCServClosingDays
        arguments: ["@doctrine.orm.entity_manager"]

    oc_core.validator.AntiDayDurationAfterTwoPM:                             
        class: OC\CoreBundle\Validator\AntiDayDurationAfterTwoPMValidator     
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"] 
        tags:
            - { name: validator.constraint_validator, alias: oc_core_AntiDayDurationAfterTwoPM }  

    oc_core.validator.AntiBookingAfterClosingTime:                             
            class: OC\CoreBundle\Validator\AntiBookingAfterClosingTimeValidator     
            arguments: ["@request_stack", "@doctrine.orm.entity_manager"] 
            tags:
                - { name: validator.constraint_validator, alias: oc_core_AntiBookingAfterClosingTime }